# Generated by Django 5.2.10 on 2026-01-12 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم نوع الطلب')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع طلب',
                'verbose_name_plural': 'أنواع الطلبات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسل'), ('in_progress', 'قيد المعالجة'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان مختصر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('current_company', models.ForeignKey(blank=True, help_text='تحدد من عليه الدور الآن (شركة العميل أو شركة التوريد).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_requests', to='accounts.company', verbose_name='الجهة الحالية المسؤولة')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='vendors.worker', verbose_name='العامل')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='requests.requesttype', verbose_name='نوع الطلب')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='اسم الحقل (للواجهة)')),
                ('key', models.SlugField(max_length=80, verbose_name='مفتاح الحقل')),
                ('field_type', models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ'), ('bool', 'نعم/لا'), ('choice', 'قائمة خيارات'), ('json', 'بيانات مركبة')], max_length=20, verbose_name='نوع الحقل')),
                ('is_required', models.BooleanField(default=False, verbose_name='إلزامي')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='مساعدة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('choices', models.JSONField(blank=True, null=True, verbose_name='الخيارات')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='requests.requesttype', verbose_name='نوع الطلب')),
            ],
            options={
                'verbose_name': 'حقل نوع طلب',
                'verbose_name_plural': 'حقول أنواع الطلبات',
                'ordering': ('request_type', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RequestFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='قيمة نصية')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قيمة رقمية')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='قيمة تاريخ')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='قيمة نعم/لا')),
                ('value_json', models.JSONField(blank=True, null=True, verbose_name='قيمة JSON')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='requests.requestfield', verbose_name='الحقل')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='requests.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'قيمة حقل طلب',
                'verbose_name_plural': 'قيم حقول الطلبات',
                'constraints': [models.UniqueConstraint(fields=('request', 'field'), name='uq_request_field_value')],
            },
        ),
        migrations.AddConstraint(
            model_name='requestfield',
            constraint=models.UniqueConstraint(fields=('request_type', 'key'), name='uq_requestfield_type_key'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', 'created_at'], name='requests_re_status_6f423a_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['worker', 'created_at'], name='requests_re_worker__88a0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['request_type', 'created_at'], name='requests_re_request_622aba_idx'),
        ),
    ]
