# Generated by Django 5.2.10 on 2026-01-12 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('requests', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestfield',
            options={'ordering': ('request_type', 'sort_order'), 'verbose_name': 'حقل طلب', 'verbose_name_plural': 'حقول الطلبات'},
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='requests_re_status_6f423a_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='requests_re_worker__88a0d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='requests_re_request_622aba_idx',
        ),
        migrations.AddField(
            model_name='request',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_requests', to=settings.AUTH_USER_MODEL, verbose_name='أُغلق بواسطة'),
        ),
        migrations.AddField(
            model_name='request',
            name='closure_note',
            field=models.TextField(blank=True, verbose_name='ملاحظة الإغلاق'),
        ),
        migrations.AddField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى (غير مفعل حاليًا)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='current_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_requests', to='accounts.company', verbose_name='الجهة الحالية المسؤولة'),
        ),
        migrations.AlterField(
            model_name='requestfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ'), ('bool', 'نعم / لا'), ('choice', 'قائمة خيارات'), ('json', 'بيانات مركبة')], max_length=20, verbose_name='نوع الحقل'),
        ),
        migrations.AlterField(
            model_name='requestfield',
            name='label',
            field=models.CharField(max_length=150, verbose_name='اسم الحقل (للعرض)'),
        ),
        migrations.AlterField(
            model_name='requestfieldvalue',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True, verbose_name='قيمة نعم / لا'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='requests_re_status_039311_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['request_type'], name='requests_re_request_3cec5e_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['worker'], name='requests_re_worker__e6db9a_idx'),
        ),
    ]
