# Generated by Django 5.2.10 on 2026-01-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_requestfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='return_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الإعادة/النقص'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسل'), ('in_progress', 'قيد المعالجة'), ('returned', 'معاد (لوجود نقص)'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
