# Generated by Django 5.2.10 on 2026-01-16 23:20

import requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_requestattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestattachment',
            name='file',
            field=models.FileField(upload_to=requests.models.get_attachment_upload_path, verbose_name='الملف'),
        ),
    ]
