# Generated by Django 5.2.10 on 2026-01-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='اسم مسؤول التواصل')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='رقم التواصل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('company', models.OneToOneField(limit_choices_to={'company_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to='accounts.company', verbose_name='شركة التوريد')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم العامل')),
                ('iqama_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الإقامة')),
                ('nationality', models.CharField(max_length=100, verbose_name='الجنسية')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('insurance_class', models.CharField(choices=[('vip', 'VIP'), ('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=10, verbose_name='فئة التأمين')),
                ('iqama_expiry_date', models.DateField(verbose_name='تاريخ انتهاء الإقامة')),
                ('status', models.CharField(choices=[('active', 'على رأس العمل'), ('vacation', 'إجازة'), ('exit_final', 'خروج نهائي'), ('terminated', 'منتهي التعاقد')], default='active', max_length=20, verbose_name='حالة العامل')),
                ('joined_at', models.DateField(verbose_name='تاريخ المباشرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='vendors.vendor', verbose_name='شركة التوريد')),
            ],
        ),
    ]
