# Generated by Django 5.2.10 on 2026-01-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='clients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'company_type': 'client'}, related_name='contracted_vendors', to='accounts.company', verbose_name='العملاء المتعاقد معهم'),
        ),
    ]
