# Generated by Django 5.2.10 on 2026-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profiles/'),
        ),
    ]
