# Generated by Django 5.2.10 on 2026-01-19 15:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة الملف التعريفي'),
        ),
    ]
